#!/usr/bin/python
# -*- coding: utf-8 -*-

import numpy as np


def dual_intersections(points):
    """
    calculates all intersections generated by the point set.

    Generates tuples of (x_intersect, y_intersect, pointA, pointB)
    """

    totalpoints = len(points)
    for index, point in enumerate(points):
        a1, b1 = point
        for second_point in points[index+1:]: #from index + 1 to the end of the list
            a2, b2 = second_point
            x = (b2-b1)/(a1-a2)
            y = a1*x + b1
            yield (x, y, point, second_point)
def line_intersect(point, point_set):
    """
    For a given point, calculate intersections with the point set.
    """
    a1, b1 = point
    for index, second_point in enumerate(point_set):
        print "comparing", point, second_point
        print np.array_equal(second_point, point)
        if np.array_equal(second_point, point):
            continue
        a2, b2 = second_point
        x = (b2-b1)/(a1-a2)
        y = a1*x + b1
        yield (x, y, second_point)

def points_to_pos_and_angle(points):
    support_points =  [ (0.0, point[1]) for point in points] # list of points where the lines run through
    line_angles = np.arctan(points[:, 0]) * 180.0 / np.pi # WHYEVER pyqtgraph expects angles in DEGREE
    for idx, p in enumerate(support_points):
        angle = line_angles[idx]
    return support_points, line_angles

def median_line(points):
    """
    for a given set of points, find the line segments of the median line
    """
    ## first step: left limes median line (left of first intersection)
    # We observe that for x << (leftest intersection), the slope of the line defines its order.
    # so we take the lazy route and sort our lines by slope, which is the x_1 coordinate of each point
    lefthand_lines_sorted = sorted(points, key=lambda p: p[0])
    median = len(points) / 2 # is floor(#points/2), so alright for odd numbers
    ## ok, let's get all the intersection points, too
    print lefthand_lines_sorted[median]
    intersections = line_intersect(lefthand_lines_sorted[median], lefthand_lines_sorted)
    leftest_intersection = min(intersections, key = lambda intersect: intersect[0])
    return leftest_intersection
    


